# -*- coding: utf-8 -*-
"""TTS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sTVSCzVBNFvBNHr29OX1sWmjXFO_u_7P
"""

!pip install -q streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import random
# 
# # Konfigurasi Halaman
# st.set_page_config(page_title="TTS Alkitab Cak Lontong", page_icon="📖", layout="centered")
# 
# # Data Soal
# questions = [
#     {
#         "q": "Karena tidak mau pergi ke Niniwe, Nabi Yunus akhirnya ditelan oleh ikan...",
#         "normal": "BESAR", "lontong": "HIDUP",
#         "reason": "Kalau ikannya udah mati, dia ngambang doang di laut, mana bisa buka mulut buat nelen orang."
#     },
#     {
#         "q": "Saat dikejar pasukan Firaun, dengan tongkatnya Nabi Musa membelah laut...",
#         "normal": "MERAH", "lontong": "DALAM",
#         "reason": "Justru karena lautnya dalam makanya harus dibelah biar bisa lewat. Kalau cetek tinggal nyeker aja."
#     },
#     {
#         "q": "Hukuman untuk Daniel karena tetap berdoa kepada Allah adalah dilempar ke dalam gua...",
#         "normal": "SINGA", "lontong": "GELAP",
#         "reason": "Gua zaman dulu ditutup batu atasnya, ya pasti gelap gulita. Kalau terang banyak lampu itu minimarket."
#     },
#     {
#         "q": "Simson akhirnya kehilangan semua kekuatannya setelah rambutnya di...",
#         "normal": "POTONG", "lontong": "PENDEK",
#         "reason": "Setelah dicukur ya rambutnya jadi pendek. Coba kalau potong ujungnya doang dikit, kekuatannya nggak hilang."
#     },
#     {
#         "q": "Karena badannya pendek, Zakheus memanjat pohon ara supaya bisa melihat...",
#         "normal": "YESUS", "lontong": "JELAS",
#         "reason": "Kalau lihat dari bawah ketutupan kepala orang, buram! Makanya manjat supaya bisa melihat dengan jelas."
#     },
#     {
#         "q": "Saat berjalan di atas air menuju Yesus lalu melihat tiupan angin sakal, Petrus menjadi...",
#         "normal": "TAKUT", "lontong": "BASAH",
#         "reason": "Karena mulai tenggelam ke dalam air, ya otomatis baju sampai sepatunya basah kuyup!"
#     },
#     {
#         "q": "Tindakan Yudas Iskariot rela menyerahkan Yesus kepada imam-imam kepala demi mendapatkan 30 keping...",
#         "normal": "PERAK", "lontong": "SALAH",
#         "reason": "Ya jelas tindakannya salah! Masa mengkhianati Guru sendiri cuma demi materi."
#     },
#     {
#         "q": "Meskipun diuji dengan kehilangan seluruh hartanya dan anak-anaknya meninggal, Ayub tetap...",
#         "normal": "SETIA", "lontong": "HIDUP",
#         "reason": "Yang mati anak dan ternaknya. Ayubnya sendiri kan saat itu masih hidup."
#     },
#     {
#         "q": "Esau rela menjual hak kesulungannya kepada Yakub hanya demi semangkuk sayur kacang...",
#         "normal": "MERAH", "lontong": "PANAS",
#         "reason": "Kuahnya pasti masih panas dan ngebul. Kalau udah dingin dari kemarin, Esau juga mikir dua kali."
#     },
#     {
#         "q": "Nabi Elia sendirian menantang 450 nabi palsu dewa Baal di atas Gunung...",
#         "normal": "KARMEL", "lontong": "BERANI",
#         "reason": "Satu lawan empat ratus lima puluh orang, ya jelas Elia itu berani! Kalau penakut mending ngumpet."
#     },
#     {
#         "q": "Sebelum merayakan Paskah, Yesus memberi teladan kerendahan hati dengan membasuh kaki...",
#         "normal": "MURID", "lontong": "KOTOR",
#         "reason": "Zaman dulu jalanan berdebu dan cuma pakai sandal, kakinya pasti kotor. Kalau bersih ngapain dibasuh lagi."
#     },
#     {
#         "q": "Martir pertama di gereja mula-mula yang mati syahid karena dilempari batu bertubi-tubi oleh orang Yahudi...",
#         "normal": "STEFANUS", "lontong": "BERDARAH",
#         "reason": "Dilempar batu sekepalan tangan beramai-ramai, ya pasti badannya berdarah semua."
#     },
#     {
#         "q": "Untuk bisa masuk ke tanah Kanaan, bangsa Israel yang dipimpin Yosua berjalan menyeberangi sungai...",
#         "normal": "YORDAN", "lontong": "KERING",
#         "reason": "Kalau airnya lagi deres mana berani bawa anak-anak nyeberang. Nunggu air berhenti dan tanahnya kering baru nyeberang!"
#     }
# ]
# 
# # Inisialisasi State Session
# if 'current_idx' not in st.session_state:
#     st.session_state.current_idx = 0
#     st.session_state.show_hint = False
#     st.session_state.hint_index = -1
#     st.session_state.is_correct = False
# 
# def next_question():
#     st.session_state.current_idx += 1
#     st.session_state.show_hint = False
#     st.session_state.hint_index = -1
#     st.session_state.is_correct = False
# 
# def calculate_hint(normal, lontong):
#     # Cari huruf yang posisinya sama persis
#     matches = [i for i in range(len(lontong)) if i < len(normal) and normal[i] == lontong[i]]
#     if matches:
#         return matches[0] # Ambil match pertama
#     else:
#         # Jika tidak ada yang sama, random selain index 0
#         return random.randint(1, len(lontong) - 1) if len(lontong) > 1 else 0
# 
# st.title("🧩 TTS Alkitab Nyeleneh")
# 
# if st.session_state.current_idx < len(questions):
#     q_data = questions[st.session_state.current_idx]
#     ans_lontong = q_data['lontong'].upper()
#     ans_normal = q_data['normal'].upper()
# 
#     # Header Contoh / Soal
#     if st.session_state.current_idx < 2:
#         st.subheader(f"💡 CONTOH SOAL {st.session_state.current_idx + 1}")
#         st.info("Pemanasan dulu! Gunakan logika yang di luar nalar.")
#     else:
#         st.subheader(f"🎯 SOAL NOMOR {st.session_state.current_idx - 1}")
# 
#     # Tampilkan Pertanyaan
#     st.write(f"**Pertanyaan:** {q_data['q']}")
# 
#     # Hitung Hint jika belum diset
#     if st.session_state.hint_index == -1:
#         st.session_state.hint_index = calculate_hint(ans_normal, ans_lontong)
# 
#     # Tampilan Kotak Huruf
#     boxes = []
#     for i in range(len(ans_lontong)):
#         if st.session_state.show_hint and i == st.session_state.hint_index:
#             boxes.append(f" **[ {ans_lontong[i]} ]** ")
#         else:
#             boxes.append(" [ _ ] ")
# 
#     st.markdown("### " + "".join(boxes))
#     st.caption(f"*Jumlah kotak: {len(ans_lontong)} huruf*")
# 
#     # Input Jawaban
#     user_input = st.text_input("Ketik jawabanmu di sini:", key=f"input_{st.session_state.current_idx}").upper()
# 
#     col1, col2 = st.columns([1, 1])
# 
#     with col1:
#         if st.button("Kunci Jawaban ✅"):
#             if user_input == ans_lontong:
#                 st.session_state.is_correct = True
#             else:
#                 st.error("Tetooot! ❌ Salah! Jangan pakai logika lurus, coba pakai logika Cak Lontong.")
# 
#     with col2:
#         if not st.session_state.is_correct:
#             if st.button("Minta Hint 💡"):
#                 st.session_state.show_hint = True
#                 st.rerun()
# 
#     # Jika Benar
#     if st.session_state.is_correct:
#         st.success("BENAR! 🎉")
#         st.warning(f"**Alasan Logis:** {q_data['reason']}")
#         if st.button("Lanjut Soal Berikutnya ➡️"):
#             next_question()
#             st.rerun()
# 
# else:
#     st.success("🎊 Selamat! Kamu telah menyelesaikan semua pertanyaan.")
#     st.balloons()
#     if st.button("Main Lagi 🔄"):
#         st.session_state.current_idx = 0
#         st.rerun()